-- MySQL Script generated by MySQL Workbench
-- sáb 10 jun 2017 11:23:34 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema telo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema telo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `telo` DEFAULT CHARACTER SET utf8 ;
USE `telo` ;

-- -----------------------------------------------------
-- Table `telo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `verified` TINYINT(1) NOT NULL DEFAULT 0,
  `photo` VARCHAR(300) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  `remember_token` VARCHAR(300) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `verified` TINYINT(1) NOT NULL DEFAULT 0,
  `password` VARCHAR(100) NOT NULL,
  `remember_token` VARCHAR(300) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`countries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`provinces` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provinces_countries_idx` (`country_id` ASC),
  CONSTRAINT `fk_provinces_countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `telo`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`cities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `province_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cities_provinces1_idx` (`province_id` ASC),
  CONSTRAINT `fk_cities_provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `telo`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`establishments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`establishments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `hint` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `city_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_establisments_customers1_idx` (`customer_id` ASC),
  INDEX `fk_establisments_cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_establisments_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `telo`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establisments_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `telo`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`coupons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `description` VARCHAR(200) NULL,
  `value` VARCHAR(45) NULL,
  `expiration_date` DATETIME NOT NULL,
  `establishment_id` INT UNSIGNED NOT NULL,
  `foto` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coupons_establishments1_idx` (`establishment_id` ASC),
  CONSTRAINT `fk_coupons_establishments1`
    FOREIGN KEY (`establishment_id`)
    REFERENCES `telo`.`establishments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`payment_methods_enterprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`payment_methods_enterprises` (
  `cash` TINYINT(1) NOT NULL,
  `debit_card` TINYINT(1) NOT NULL,
  `credit_card` TINYINT(1) NOT NULL,
  `establisment_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  INDEX `fk_payment_methods_enterprises_establisments1_idx` (`establisment_id` ASC),
  CONSTRAINT `fk_payment_methods_enterprises_establisments1`
    FOREIGN KEY (`establisment_id`)
    REFERENCES `telo`.`establishments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telo`.`redentions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telo`.`redentions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `coupon_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_redentions_coupons1_idx` (`coupon_id` ASC),
  INDEX `fk_redentions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_redentions_coupons1`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `telo`.`coupons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redentions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `telo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
