version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"  # Render requiere exponer el puerto 10000
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${RENDER_EXTERNAL_URL}  # Variable automática de Render
      - DB_CONNECTION=pgsql
      - DB_HOST=db  # Nombre del servicio PostgreSQL
      - DB_PORT=5432
      - DB_DATABASE=telo_backend
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=telo_backend
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
